// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function GetClientStatus(arg1) {
  return window['go']['main']['App']['GetClientStatus'](arg1);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartClient(arg1) {
  return window['go']['main']['App']['StartClient'](arg1);
}

export function StopClient(arg1) {
  return window['go']['main']['App']['StopClient'](arg1);
}
