// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearLogs():Promise<void>;

export function DeleteConfig(arg1:string):Promise<void>;

export function GetClientStatus(arg1:string):Promise<Record<string, any>>;

export function GetLogs():Promise<Array<string>>;

export function GetVersion():Promise<string>;

export function ListConfigs():Promise<Array<main.NPCConfig>>;

export function SaveConfig(arg1:main.NPCConfig):Promise<void>;

export function StartClient(arg1:string):Promise<void>;

export function StopClient(arg1:string):Promise<void>;
